<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>All Test Cases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>df88b384-4db8-4c82-b255-0afa0fd22006</testSuiteGuid>
   <testCaseLink>
      <guid>d4b483d9-b0f3-4b3c-857f-9da545bcefbb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcase/Creat successful</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fdfd51b9-fd2a-4191-8fde-534f6ae8bf5d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ListUser</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>fdfd51b9-fd2a-4191-8fde-534f6ae8bf5d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>9d9955ac-b2ac-4526-b13a-0af93b896b4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dcc558b2-6e7a-4ee2-97e1-d69029701727</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcase/Creat successful</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d9955ac-b2ac-4526-b13a-0af93b896b4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>927e6975-1aad-4819-a64a-b7f299abc612</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcase/Create a new user</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0de4fa76-1864-4d5e-aa8a-70ad8f4f4342</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>086a27a9-05ed-4e07-8465-e17bddfdeac1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>311c2780-afd0-4352-a23f-fc00c2c42271</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcddbada-1d5e-422c-b810-55f7c48bb931</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b3cb3f6-19ff-4f44-ae2c-a1c680bd3044</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dbfdbe28-9c52-4b9a-a4a7-c776c438be0c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcase/Login Unseccessful</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
