<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Flow</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2bc2b4cb-a055-4fe4-ab2b-b17ac89832f1</testSuiteGuid>
   <testCaseLink>
      <guid>65c817cb-8a1f-467c-98c9-5e7e54908c94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Flow/Register Successfull</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2051b439-6cb9-4b5c-adeb-0f402a4d8213</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/account</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>2051b439-6cb9-4b5c-adeb-0f402a4d8213</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>4e39b6e3-96e4-4e89-8614-f10b56abc45e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2051b439-6cb9-4b5c-adeb-0f402a4d8213</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>0d4fbaef-f4b7-44a3-864c-0376945056c8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
